import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavbarCustom from '@/components/Navbar'
import FooterCustom from '@/components/FooterCustom'
import { UserProvider } from '@/context/userContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <NavbarCustom />
          <div className='md:pt-[12vh] lg:pt-[12vh] pt-[10vh]'>
            {children}
          </div>

          <FooterCustom />
        </UserProvider>
      </body>
    </html>
  )
}
